# Generated by Django 2.1.7 on 2019-02-26 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('address', models.CharField(max_length=50, verbose_name='活动地址')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Activities_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('guests', models.ManyToManyField(blank=True, related_name='activities_guest', to=settings.AUTH_USER_MODEL, verbose_name='嘉宾')),
                ('signed_in_users', models.ManyToManyField(blank=True, related_name='activities_signed_in', to=settings.AUTH_USER_MODEL, verbose_name='已签到嘉宾')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
                'ordering': ('-add_time',),
            },
        ),
    ]
