# Generated by Django 2.1.7 on 2019-02-26 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20190226_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否开启签到'),
        ),
    ]
